// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMDB_API.Repository;

#nullable disable

namespace TMDB_API.Migrations
{
    [DbContext(typeof(TmdbContext))]
    partial class TmdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMDB_API.Models.Credit", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cast");

                    b.Property<string>("Crew")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("crew");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.HasKey("MovieId");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("TMDB_API.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Budget")
                        .HasColumnType("int")
                        .HasColumnName("budget");

                    b.Property<string>("Genres")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("genres");

                    b.Property<string>("Homepage")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("homepage");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keywords");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("original_language");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("original_title");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("overview");

                    b.Property<double?>("Popularity")
                        .HasColumnType("float")
                        .HasColumnName("popularity");

                    b.Property<string>("PosterPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<long?>("Revenue")
                        .HasColumnType("bigint")
                        .HasColumnName("revenue");

                    b.Property<int?>("Runtime")
                        .HasColumnType("int")
                        .HasColumnName("runtime");

                    b.Property<string>("SpokenLanguages")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("spoken_languages");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Tagline")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.Property<double?>("VoteAverage")
                        .HasColumnType("float")
                        .HasColumnName("vote_average");

                    b.Property<short?>("VoteCount")
                        .HasColumnType("smallint")
                        .HasColumnName("vote_count");

                    b.HasKey("Id");

                    b.HasIndex("VoteCount");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("TMDB_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TMDB_API.Models.UserFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("TMDB_API.Models.UserFavorite", b =>
                {
                    b.HasOne("TMDB_API.Models.Movie", "Movie")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMDB_API.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMDB_API.Models.Movie", b =>
                {
                    b.Navigation("FavoritedBy");
                });

            modelBuilder.Entity("TMDB_API.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
